baseurl = "https://yuankun.me"
title = "Yuankun's Blog"
paginate = 10
theme = "PaperMod"
pygmentsUseClasses = true

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[minify]
  disableXML = true
  minifyOutput = true

[markup.highlight]
  noClasses = false
# anchorLineNos = true
# codeFences = true
# guessSyntax = true
# lineNos = true
# style = monokai

[params]
  env = "production"
  title = "Yuankun's Blog"
  description = "Always do what you're afraid to do"
  keywords = ["blog", "thinking", "programming"]
  author = "Yuankun"
  dateFormat = "January 2, 2006"
  defaultTheme = "light"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.homeInfoParams]
  title = "Do or do not, there is no try"
  content = "Always do what you're afraid to do."

[[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/756651"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/yuankunzhang"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  name = "Search"
  identifier = "search"
  url = "/search/"
  weight = 10

[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 20

[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 30

[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 40

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 50
