baseurl = "https://yuankun.me"
title = "yuankun@net: ~$"
theme = "DoIt"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20

#[markup.highlight]
#style = "github-dark"

[params]
  author = "Yuankun Zhang"
  info = "Coder, Runner"
  title = "yuankun@net: ~$"
  description = "Always do what you're afraid to do"
  keywords = "code,read,life"

  # DoIt theme version
  version = "0.3.X"
  enablePWA = false

[params.home.profile]
  enable = false

[params.analytics]
  enable = true

[params.analytics.google]
  id = "G-ZXQSK4ST20"
  anonymizeIP = false

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  lineNumbersInTable = true
  noClasses = false

#[taxonomies]
#  category = "categories"
#  series = "series"
#  tag = "tags"
#  author = "authors"

[params.page.comment]
  enable = true

[params.page.comment.utterances]
  enable = true
  repo = "yuankunzhang/blog"
  issueTerm = "pathname"
  label = "comment"
  lightTheme = "github-light"
  darkTheme = "github-dark"

## Social links
#[[params.social]]
#  name = "Github"
#  icon = "fa fa-github fa-2x"
#  weight = 1
#  url = "https://github.com/yuankunzhang/"
#[[params.social]]
#  name = "stackoverflow"
#  icon = "fa fa-stack-overflow fa-2x"
#  weight = 2
#  url = "https://stackoverflow.com/users/756651"

[author]
  name = "yuankun"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Linux Syscalls"
  weight = 3
  url = "syscall64/"
