baseURL = "https://yuankun.me/"
languageCode = "en-us"
title = "Yuankun's Blog"
theme = "slick"

[taxonomies]
    tags = "tags"

[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 1

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        title = "All tags"
        url = "/tags/"
        weight = 2

    [[menu.main]]
        identifier = "whoami"
        name = "Whoami"
        title = "Whoami"
        url = "/whoami/"
        weight = 3


    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 1


    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Theme repository"
        url = "https://github.com/yuankunzhang"
        weight = 1
